set(PHOTOSHOP_SDK_ROOT "${CMAKE_SOURCE_DIR}/dependencies/photoshop-sdk/pluginsdk" CACHE PATH "Photoshop SDK pluginsdk folder")
set(LCMS_ROOT "${CMAKE_SOURCE_DIR}/dependencies/lcms/lcms2-2.19.1" CACHE PATH "Little CMS 2.19.1 source")
foreach(required "${PHOTOSHOP_SDK_ROOT}/photoshopapi/photoshop/PIFilter.h" "${LCMS_ROOT}/include/lcms2.h")
    if(NOT EXISTS "${required}")
        message(FATAL_ERROR "Missing Photoshop dependency: ${required}")
    endif()
endforeach()
file(READ "${CMAKE_SOURCE_DIR}/resources/photoshop-pipl.json" photoshop_pipl)
string(JSON photoshop_pipl SET "${photoshop_pipl}" PiPLs 0 ComponentVersionShortNum ${PROJECT_VERSION_MAJOR})
string(JSON photoshop_pipl SET "${photoshop_pipl}" PiPLs 0 ComponentVersionMinorRevNum ${PROJECT_VERSION_MINOR})
string(JSON photoshop_pipl SET "${photoshop_pipl}" PiPLs 0 ComponentVersionDotRevNum ${PROJECT_VERSION_PATCH})
file(WRITE "${CMAKE_BINARY_DIR}/generated/photoshop-pipl-versioned.json" "${photoshop_pipl}\n")
enable_language(C)
file(GLOB lcms_sources CONFIGURE_DEPENDS "${LCMS_ROOT}/src/*.c")
add_library(photoshop_lcms STATIC ${lcms_sources})
target_include_directories(photoshop_lcms PUBLIC "${LCMS_ROOT}/include")
set_property(TARGET photoshop_lcms PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
set(ps_includes "${PHOTOSHOP_SDK_ROOT}/photoshopapi/photoshop" "${PHOTOSHOP_SDK_ROOT}/photoshopapi/pica_sp" src/host src/photoshop src/neural "${NGX_SDK_ROOT}/include")
add_library(DLSS5_Photoshop MODULE src/photoshop/filter.cpp src/photoshop/dialog.cpp src/photoshop/tiled_image.cpp
    src/photoshop/color_pipeline.cpp src/host/neural_bridge.cpp src/host/finishing.cpp src/host/update_notice.cpp
    src/neural/Feature18Runtime.cpp resources/photoshop.rc resources/version.rc)
target_include_directories(DLSS5_Photoshop PRIVATE ${ps_includes} resources)
target_link_libraries(DLSS5_Photoshop PRIVATE photoshop_lcms d3d12 dxgi version shell32 ole32 comctl32
    "${NGX_SDK_ROOT}/lib/Windows_x86_64/x64/nvsdk_ngx_s.lib")
set_target_properties(DLSS5_Photoshop PROPERTIES PREFIX "" SUFFIX ".8bf" OUTPUT_NAME "4x4Tools-DLSS5-Photoshop")
apply_compiler_flags(DLSS5_Photoshop)
# SDK documentation comments are supplied in a legacy Windows encoding.
target_compile_options(DLSS5_Photoshop PRIVATE /wd4828)
target_compile_definitions(DLSS5_Photoshop PRIVATE PHOTOSHOP_FILTER)
add_custom_command(TARGET DLSS5_Photoshop POST_BUILD
    COMMAND "${CMAKE_COMMAND}" -E make_directory "$<TARGET_FILE_DIR:DLSS5_Photoshop>/runtime"
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${NR_RUNTIME_FILE}" "$<TARGET_FILE_DIR:DLSS5_Photoshop>/runtime/nvngx_dlssnr.dll" VERBATIM)
add_executable(photoshop_host_test tests/photoshop_host_test.cpp)
target_include_directories(photoshop_host_test PRIVATE ${ps_includes})
apply_compiler_flags(photoshop_host_test)
target_compile_options(photoshop_host_test PRIVATE /wd4828)
add_test(NAME photoshop_host_contract COMMAND photoshop_host_test "$<TARGET_FILE:DLSS5_Photoshop>")
add_test(NAME photoshop_neural_hardware COMMAND photoshop_host_test "$<TARGET_FILE:DLSS5_Photoshop>" --neural)
set_tests_properties(photoshop_host_contract PROPERTIES TIMEOUT 90)
set_tests_properties(photoshop_neural_hardware PROPERTIES TIMEOUT 180)
